language: c
compiler:
    - gcc

git:
    - git clone --depth=50 --branch=structure git://github.com/jhmatthews/python.git jhmatthews/python
    - mkdir progs
    - cd progs
    - git clone git://github.com/jhmatthews/python.git

#env:
#    - PYTHON = $TRAVIS_BUILD_DIR

#branches:
#  only:
#    - structure


install:
    # First make cfitsio library
    - echo $PYTHON
    - export PYTHON=$TRAVIS_BUILD_DIR
    - cd software/cfitsio3040
    -  ./configure 
    - make
    - mv libcfitsio.a ../../lib
    - make clean

    # Then make GSL library
    - cd ../../software/gsl-1.15
    - ./configure --disable-shared --prefix=$PYTHON/gsl
    - make
    - make check 2>&1
    - make install
    - make clean

script:
    - export PYTHON=$TRAVIS_BUILD_DIR
    - cd $PYTHON/progs/python
    - make CC=gcc python
    - make clean
    - make CC=gcc py_wind